### ISSUE TITLE
declare statement causes "Could not locate namespace definition for class ..." exception

### ISSUE THREAD

**Issue by mkhyman** [KKSzymanowski/Traitor#11]
When (via santigarcor/laratrust) trying to get the namespace in a file with a declare statement an exception is thrown.

I have not tested it in isolation so it may be caused by how laratrust is using this package, if so sorry.

Handlers/AbstractTreeHandler.php
line : 193
function: retrieveNamespace

Steps to reproduce:
1. Create a class with "declare(strict_types=1);" as 1st line after php opening tag.
2. Try to insert a trait programmatically.

Removing the declare statement and adding it in manually afterwards is a workaround.

Had a quick look at the code and it seems that the assumption is that namespace is always the first parsed item in the class.

**Comment by KKSzymanowski** [comment]
Are you using Laratrust 7?

I have a fix ready but I need to know on which branches in Laratrust should I create a PR to update to a newer version. The current version was created for some no longer supported PHP versions and a version bump means breaking BC and therefore new major version.

**Comment by mkhyman** [comment]
Yes I am using Laratrust 7.

**Comment by KKSzymanowski** [comment]
I suppose you added the trait manually by now but if you want to know if it's fixed in Latatrust please follow this PR: https://github.com/santigarcor/laratrust/pull/550

**Comment by mkhyman** [comment]
Yes i added it manually, I just thought it would be useful for you to know so you could make it more robust, in case there are other lovers of strict typing out there. I appreciate the quick turn around.
